export const character = {
	name: "Vendethial",
	race: "Half-Elf",
	class: "Bard",
	level: 4,
	background: "Charlatan",
	alignment: "Chaotic-Nuetral",
	specialization: "College Of Whispers",
	experiencePoints: 2700,
	armorClass: "Leather",
	armorClassDextMod: 6,
	AC: 15,
	initiative: "",
	speed: 30,
	specialAbilities: ["Dark Vision 60ft"],
	hitPoints: {
		current: 21,
		maximum: 21,
		temporary: "",
	},
	hitDice: ["8", "8", "8"],
	specialBonusAction: "8", // from psychic blades
	proficiencyBonus: 2,
	abilityModifier: {
		strength: -1,
		dexterity: 4,
		constitution: 1,
		intelligence: 2,
		wisdom: 2,
		charisma: 5,
	},
	proficiencies: ["Simple Weapons", "Longsword", "Crossbow"],
	languages: [],
	abilities: {
		strength: 8,
		dexterity: 18,
		constitution: 12,
		intelligence: 14,
		wisdom: 14,
		charisma: 20,
	},
	skills: {
		acrobatics: 6,
		animalHandling: 3,
		arcana: 3,
		athletics: 0,
		deception: 7,
		history: 3,
		insight: 3,
		intimidation: 7,
		investigation: 3,
		medicine: 3,
		nature: 3,
		perception: 6,
		performance: 6,
		persuasion: 9,
		religion: 3,
		sleightOfHand: 6,
		stealth: 6,
		survival: 3,
	},
	passivePerception: 1,
	passiveInsight: 10,
	equipment: ["Rapier", "Weighted Dice"],
	traits: ["", "", ""],
	bonds: [""],
	flaws: [""],

	ideals: [""],

	spells: [
		{
			higher_level: [],
			index: "prestidigitation",
			name: "Prestidigitation",
			desc: [
				"This spell is a minor magical trick that novice spellcasters use for practice. You create one of the following magical effects within 'range':",
				"You create an instantaneous, harmless sensory effect, such as a shower of sparks, a puff of wind, faint musical notes, or an odd odor.",
				"You instantaneously light or snuff out a candle, a torch, or a small campfire.",
				"You instantaneously clean or soil an object no larger than 1 cubic foot.",
				"You chill, warm, or flavor up to 1 cubic foot of nonliving material for 1 hour.",
				"You make a color, a small mark, or a symbol appear on an object or a surface for 1 hour.",
				"You create a nonmagical trinket or an illusory image that can fit in your hand and that lasts until the end of your next turn.",
				"If you cast this spell multiple times, you can have up to three of its non-instantaneous effects active at a time, and you can dismiss such an effect as an action.",
			],
			range: "10 feet",
			components: ["V", "S"],
			ritual: false,
			duration: "1 hour",
			concentration: false,
			casting_time: "1 action",
			level: 0,
			school: {
				index: "transmutation",
				name: "Transmutation",
				url: "/api/magic-schools/transmutation",
			},
			classes: [
				{ index: "bard", name: "Bard", url: "/api/classes/bard" },
				{ index: "sorcerer", name: "Sorcerer", url: "/api/classes/sorcerer" },
				{ index: "warlock", name: "Warlock", url: "/api/classes/warlock" },
				{ index: "wizard", name: "Wizard", url: "/api/classes/wizard" },
			],
			subclasses: [{ index: "lore", name: "Lore", url: "/api/subclasses/lore" }],
			url: "/api/spells/prestidigitation",
		},
		{
			higher_level: [],
			index: "minor-illusion",
			name: "Minor Illusion",
			desc: [
				"You create a sound or an image of an object within range that lasts for the duration. The illusion also ends if you dismiss it as an action or cast this spell again.",
				"If you create a sound, its volume can range from a whisper to a scream. It can be your voice, someone else's voice, a lion's roar, a beating of drums, or any other sound you choose. The sound continues unabated throughout the duration, or you can make discrete sounds at different times before the spell ends.",
				"If you create an image of an object--such as a chair, muddy footprints, or a small chest--it must be no larger than a 5-foot cube. The image can't create sound, light, smell, or any other sensory effect. Physical interaction with the image reveals it to be an illusion, because things can pass through it.",
				"If a creature uses its action to examine the sound or image, the creature can determine that it is an illusion with a successful Intelligence (Investigation) check against your spell save DC. If a creature discerns the illusion for what it is, the illusion becomes faint to the creature.",
			],
			range: "30 feet",
			components: ["S", "M"],
			material: "A bit of fleece.",
			ritual: false,
			duration: "1 minute",
			concentration: false,
			casting_time: "1 action",
			level: 0,
			school: {
				index: "illusion",
				name: "Illusion",
				url: "/api/magic-schools/illusion",
			},
			classes: [
				{ index: "bard", name: "Bard", url: "/api/classes/bard" },
				{ index: "sorcerer", name: "Sorcerer", url: "/api/classes/sorcerer" },
				{ index: "warlock", name: "Warlock", url: "/api/classes/warlock" },
				{ index: "wizard", name: "Wizard", url: "/api/classes/wizard" },
			],
			subclasses: [{ index: "lore", name: "Lore", url: "/api/subclasses/lore" }],
			url: "/api/spells/minor-illusion",
		},
		{
			higher_level: [],
			index: "comprehend-languages",
			name: "Comprehend Languages",
			desc: [
				"For the duration, you understand the literal meaning of any spoken language that you hear. You also understand any written language that you see, but you must be touching the surface on which the words are written. It takes about 1 minute to read one page of text.",
				"This spell doesn't decode secret messages in a text or a glyph, such as an arcane sigil, that isn't part of a written language.",
			],
			range: "Self",
			components: ["V", "S", "M"],
			material: "A pinch of soot and salt.",
			ritual: true,
			duration: "1 hour",
			concentration: false,
			casting_time: "1 action",
			level: 1,
			school: {
				index: "divination",
				name: "Divination",
				url: "/api/magic-schools/divination",
			},
			classes: [
				{ index: "bard", name: "Bard", url: "/api/classes/bard" },
				{ index: "sorcerer", name: "Sorcerer", url: "/api/classes/sorcerer" },
				{ index: "warlock", name: "Warlock", url: "/api/classes/warlock" },
				{ index: "wizard", name: "Wizard", url: "/api/classes/wizard" },
			],
			subclasses: [{ index: "lore", name: "Lore", url: "/api/subclasses/lore" }],
			url: "/api/spells/comprehend-languages",
		},
		{
			index: "thunderwave",
			name: "Thunderwave",
			desc: [
				"A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you must make a constitution saving throw. On a failed save, a creature takes 2d8 thunder damage and is pushed 10 feet away from you. On a successful save, the creature takes half as much damage and isn't pushed.",
				"In addition, unsecured objects that are completely within the area of effect are automatically pushed 10 feet away from you by the spell's effect, and the spell emits a thunderous boom audible out to 300 feet.",
			],
			higher_level: [
				"When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d8 for each slot level above 1st.",
			],
			range: "Self",
			components: ["V", "S"],
			ritual: false,
			duration: "Instantaneous",
			concentration: false,
			casting_time: "1 action",
			level: 1,
			damage: {
				damage_type: {
					index: "thunder",
					name: "Thunder",
					url: "/api/damage-types/thunder",
				},
				damage_at_slot_level: {
					"1": "2d8",
					"2": "3d8",
					"3": "4d8",
					"4": "5d8",
					"5": "6d8",
					"6": "7d8",
					"7": "8d8",
					"8": "9d8",
					"9": "10d8",
				},
			},
			dc: {
				dc_type: { index: "con", name: "CON", url: "/api/ability-scores/con" },
				dc_success: "half",
			},
			area_of_effect: { type: "cube", size: 15 },
			school: {
				index: "evocation",
				name: "Evocation",
				url: "/api/magic-schools/evocation",
			},
			classes: [
				{ index: "bard", name: "Bard", url: "/api/classes/bard" },
				{ index: "druid", name: "Druid", url: "/api/classes/druid" },
				{ index: "sorcerer", name: "Sorcerer", url: "/api/classes/sorcerer" },
				{ index: "wizard", name: "Wizard", url: "/api/classes/wizard" },
			],
			subclasses: [{ index: "lore", name: "Lore", url: "/api/subclasses/lore" }],
			url: "/api/spells/thunderwave",
		},
		{
			index: "sleep",
			name: "Sleep",
			desc: [
				"This spell sends creatures into a magical slumber. Roll 5d8; the total is how many hit points of creatures this spell can affect. Creatures within 20 feet of a point you choose within range are affected in ascending order of their current hit points (ignoring unconscious creatures).",
				"Starting with the creature that has the lowest current hit points, each creature affected by this spell falls unconscious until the spell ends, the sleeper takes damage, or someone uses an action to shake or slap the sleeper awake. Subtract each creature's hit points from the total before moving on to the creature with the next lowest hit points. A creature's hit points must be equal to or less than the remaining total for that creature to be affected.",
				"Undead and creatures immune to being charmed aren't affected by this spell.",
			],
			higher_level: [
				"When you cast this spell using a spell slot of 2nd level or higher, roll an additional 2d8 for each slot level above 1st.",
			],
			range: "90 feet",
			components: ["V", "S", "M"],
			material: "A pinch of fine sand, rose petals, or a cricket.",
			ritual: false,
			duration: "1 minute",
			concentration: false,
			casting_time: "1 action",
			level: 1,
			damage: { damage_at_slot_level: { "1": "5d8" } },
			area_of_effect: { type: "sphere", size: 20 },
			school: {
				index: "enchantment",
				name: "Enchantment",
				url: "/api/magic-schools/enchantment",
			},
			classes: [
				{ index: "bard", name: "Bard", url: "/api/classes/bard" },
				{ index: "sorcerer", name: "Sorcerer", url: "/api/classes/sorcerer" },
				{ index: "wizard", name: "Wizard", url: "/api/classes/wizard" },
			],
			subclasses: [{ index: "lore", name: "Lore", url: "/api/subclasses/lore" }],
			url: "/api/spells/sleep",
		},
		{
			higher_level: [],
			index: "earthquake",
			name: "Earthquake",
			desc: [
				"You create a seismic disturbance at a point on the ground that you can see within range. For the duration, an intense tremor rips through the ground in a 100-foot-radius circle centered on that point and shakes creatures and structures in contact with the ground in that area.",
				"The ground in the area becomes difficult terrain. Each creature on the ground that is concentrating must make a constitution saving throw. On a failed save, the creature's concentration is broken.",
				"When you cast this spell and at the end of each turn you spend concentrating on it, each creature on the ground in the area must make a dexterity saving throw. On a failed save, the creature is knocked prone.",
				"This spell can have additional effects depending on the terrain in the area, as determined by the GM.",
				"Fissures. Fissures open throughout the spell's area at the start of your next turn after you cast the spell. A total of 1d6 such fissures open in locations chosen by the GM. Each is 1d10 x 10 feet deep, 10 feet wide, and extends from one edge of the spell's area to the opposite side. A creature standing on a spot where a fissure opens must succeed on a dexterity saving throw or fall in. A creature that successfully saves moves with the fissure's edge as it opens.",
				"A fissure that opens beneath a structure causes it to automatically collapse (see below).",
				"Structures. The tremor deals 50 bludgeoning damage to any structure in contact with the ground in the area when you cast the spell and at the start of each of your turns until the spell ends. If a structure drops to 0 hit points, it collapses and potentially damages nearby creatures. A creature within half the distance of a structure's height must make a dexterity saving throw. On a failed save, the creature takes 5d6 bludgeoning damage, is knocked prone, and is buried in the rubble, requiring a DC 20 Strength (Athletics) check as an action to escape. The GM can adjust the DC higher or lower, depending on the nature of the rubble. On a successful save, the creature takes half as much damage and doesn't fall prone or become buried.",
			],
			range: "500 feet",
			components: ["V", "S", "M"],
			material: "A pinch of dirt, a piece of rock, and a lump of clay.",
			ritual: false,
			duration: "Up to 1 minute",
			concentration: true,
			casting_time: "1 action",
			level: 8,
			area_of_effect: { type: "sphere", size: 100 },
			school: {
				index: "evocation",
				name: "Evocation",
				url: "/api/magic-schools/evocation",
			},
			classes: [
				{ index: "cleric", name: "Cleric", url: "/api/classes/cleric" },
				{ index: "druid", name: "Druid", url: "/api/classes/druid" },
				{ index: "sorcerer", name: "Sorcerer", url: "/api/classes/sorcerer" },
			],
			subclasses: [],
			url: "/api/spells/earthquake",
		},
		{
			higher_level: [],
			index: "hideous-laughter",
			name: "Hideous Laughter",
			desc: [
				"A creature of your choice that you can see within range perceives everything as hilariously funny and falls into fits of laughter if this spell affects it. The target must succeed on a wisdom saving throw or fall prone, becoming incapacitated and unable to stand up for the duration. A creature with an Intelligence score of 4 or less isn't affected.",
				"At the end of each of its turns, and each time it takes damage, the target can make another wisdom saving throw. The target had advantage on the saving throw if it's triggered by damage. On a success, the spell ends.",
			],
			range: "30 feet",
			components: ["V", "S", "M"],
			material: "Tiny tarts and a feather that is waved in the air.",
			ritual: false,
			duration: "Up to 1 minute",
			concentration: true,
			casting_time: "1 action",
			level: 1,
			dc: {
				dc_type: { index: "wis", name: "WIS", url: "/api/ability-scores/wis" },
				dc_success: "none",
			},
			school: {
				index: "enchantment",
				name: "Enchantment",
				url: "/api/magic-schools/enchantment",
			},
			classes: [
				{ index: "bard", name: "Bard", url: "/api/classes/bard" },
				{ index: "wizard", name: "Wizard", url: "/api/classes/wizard" },
			],
			subclasses: [{ index: "lore", name: "Lore", url: "/api/subclasses/lore" }],
			url: "/api/spells/hideous-laughter",
		},
		{
			index: "shatter",
			name: "Shatter",
			desc: [
				"A sudden loud ringing noise, painfully intense, erupts from a point of your choice within range. Each creature in a 10-foot-radius sphere centered on that point must make a Constitution saving throw. A creature takes 3d8 thunder damage on a failed save, or half as much damage on a successful one. A creature made of inorganic material such as stone, crystal, or metal has disadvantage on this saving throw.",
				"A non-magical item that is not worn or carried also suffers damage if it is in the area of the spell.",
			],
			higher_level: [
				"When you cast this spell using a 3 or higher level spell slot, the damage of the spell increases by 1d8 for each level of higher spell slot 2.",
			],
			range: "60 feet",
			components: ["V", "S", "M"],
			material: "A burst of mica.",
			ritual: false,
			duration: "Instantaneous",
			concentration: false,
			casting_time: "1 action",
			level: 2,
			damage: {
				damage_type: {
					index: "thunder",
					name: "Thunder",
					url: "/api/damage-types/thunder",
				},
				damage_at_slot_level: {
					"2": "3d8",
					"3": "4d8",
					"4": "5d8",
					"5": "6d8",
					"6": "7d8",
					"7": "8d8",
					"8": "9d8",
					"9": "10d8",
				},
			},
			dc: {
				dc_type: { index: "con", name: "CON", url: "/api/ability-scores/con" },
				dc_success: "half",
			},
			area_of_effect: { type: "sphere", size: 10 },
			school: {
				index: "evocation",
				name: "Evocation",
				url: "/api/magic-schools/evocation",
			},
			classes: [
				{ index: "bard", name: "Bard", url: "/api/classes/bard" },
				{ index: "sorcerer", name: "Sorcerer", url: "/api/classes/sorcerer" },
				{ index: "warlock", name: "Warlock", url: "/api/classes/warlock" },
				{ index: "wizard", name: "Wizard", url: "/api/classes/wizard" },
			],
			subclasses: [{ index: "lore", name: "Lore", url: "/api/subclasses/lore" }],
			url: "/api/spells/shatter",
		},
		{
			index: "blindness-deafness",
			name: "Blindness/Deafness",
			desc: [
				"You can blind or deafen a foe. Choose one creature that you can see within range to make a constitution saving throw. If it fails, the target is either blinded or deafened (your choice) for the duration. At the end of each of its turns, the target can make a constitution saving throw. On a success, the spell ends.",
			],
			higher_level: [
				"When you cast this spell using a spell slot of 3rd level or higher, you can target one additional creature for each slot level above 2nd.",
			],
			range: "30 feet",
			components: ["V"],
			ritual: false,
			duration: "1 minute",
			concentration: false,
			casting_time: "1 action",
			level: 2,
			dc: {
				dc_type: { index: "con", name: "CON", url: "/api/ability-scores/con" },
				dc_success: "none",
			},
			school: {
				index: "necromancy",
				name: "Necromancy",
				url: "/api/magic-schools/necromancy",
			},
			classes: [
				{ index: "bard", name: "Bard", url: "/api/classes/bard" },
				{ index: "cleric", name: "Cleric", url: "/api/classes/cleric" },
				{ index: "sorcerer", name: "Sorcerer", url: "/api/classes/sorcerer" },
				{ index: "wizard", name: "Wizard", url: "/api/classes/wizard" },
			],
			subclasses: [
				{ index: "lore", name: "Lore", url: "/api/subclasses/lore" },
				{ index: "fiend", name: "Fiend", url: "/api/subclasses/fiend" },
			],
			url: "/api/spells/blindness-deafness",
		},
	],
	displaySpells: [
		"blindness-deafness",
		"shatter",
		"hideous-laughter",
		"earthquake",
		"sleep",
		"prestidigitation",
		"minor-illusion",
		"comprehend-languages",
	],
}
